language: go
go:
  - 1.5.3

sudo: false

before_install:
  - go get github.com/golang/lint/golint

install: true

script:
  - go vet -x ./...
  - $HOME/gopath/bin/golint ./... | grep -v /vendor/
  - go test -v $(go list ./... | grep -v /vendor/)
  - make
  
